version: "3"
services:

  nginx:
    depends_on:
      - api
      - web
    build: proxy
    ports:
      - "80:80"

  api:
    restart: unless-stopped
    build: api
    container_name: aware
    image: sdpequinor/aware-api:latest
    volumes:
      - ./api:/src
    ports:
      - 5000:5000
    environment:
        REFRESH_INTERVAL: "15"
        FLASK_DEBUG: "True"
        DASHBOARD_HEADER: "Events"
        PROMETHEUS_API: "http://prometheus-operator-prometheus.monitoring:9090/api/v1/alerts"
        SENSU_API: "http://mon01.prod.sdp.statoil.no:8080/api/core/v2/namespaces/default/events"
        SENSU_KEY: ${SENSU_KEY}
        IGNORE_ALERTS: "TargetDown,DeadMansSwitch,KubeAPIDown,CoreDNSDown,KubeControllerManagerDown,KubeSchedulerDown"

  web:
   image: sdpequinor/aware-web:latest
   build: web
   volumes:
     - ./web/src/:/code/src
   ports:
     - 3000:3000