version: "3"
services:
  aware:
    restart: unless-stopped
    build: ./
    container_name: aware
    image: sdpequinor/aware:latest
    volumes:
      - ./src:/src
    ports:
      - 5000:5000
    environment:
        REFRESH_INTERVAL: "15"
        FLASK_DEBUG: "True"
        DASHBOARD_HEADER: "Events"
        PROMETHEUS_API: "http://prometheus-operator-prometheus.monitoring:9090/api/v1/alerts"
        IGNORE_ALERTS: "TargetDown,DeadMansSwitch,KubeAPIDown,CoreDNSDown,KubeControllerManagerDown,KubeSchedulerDown"
