apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
  namespace: monitoring
  labels:
    name: curl-pod
spec:
  containers:
  - name: curl-pod
    image: nicolaka/netshoot
    command: ["sleep"]
    args: ["999999"]
    # kubectl exec -it curl-pod -- curl http://prometheus-operator-prometheus.monitoring:9090/api/v1/alerts
