version: "3"

services:

  sensu-dashboard:
    restart: unless-stopped
    build: ../
    container_name: sensu-dashboard
    image: sensu-dashboard:latest
    volumes:
      - ../src:/app
    ports:
      - 5010:5000
    environment:
        REFRESH_INTERVAL: "60"
        DEBUG: "True"
        SENSU_API: "http://sensu-api1:4567/events,
                    http://sensu-api2:4567/events"

  uchiwa:
    container_name: uchiwa
    restart: unless-stopped
    image: uchiwa/uchiwa
    links:
      - "sensu-api1"
      - "sensu-api2"
    hostname: uchiwa
    ports:
      - "5011:3000"
    volumes:
      - ./uchiwa/:/config

  sensu-server1:
    build: .
    hostname: sensu-server1
    container_name: sensu-server1
    volumes:
      - ./sensu-server1/config.json:/etc/sensu/config.json
      - ./sensu-server1/conf.d:/etc/sensu/conf.d
    command: /opt/sensu/bin/sensu-server -c /etc/sensu/config.json

  sensu-client1:
    build: .
    hostname: sensu-client1
    container_name: sensu-client1
    volumes:
      - ./sensu-client1/config.json:/etc/sensu/config.json
      - ./sensu-client1/conf.d:/etc/sensu/conf.d
    command: /opt/sensu/bin/sensu-client -c /etc/sensu/config.json

  sensu-api1:
    build: .
    hostname: sensu-api1
    container_name: sensu-api1
    ports:
      - "4567:4567"
    volumes:
      - ./sensu-api1/config.json:/etc/sensu/config.json
      - ./sensu-api1/conf.d:/etc/sensu/conf.d
    command: /opt/sensu/bin/sensu-api -c /etc/sensu/config.json

  sensu-redis1:
    image: redis
    hostname: sensu-redis1
    container_name: sensu-redis1

  sensu-server2:
    build: .
    hostname: sensu-server2
    container_name: sensu-server2
    volumes:
      - ./sensu-server2/config.json:/etc/sensu/config.json
      - ./sensu-server2/conf.d:/etc/sensu/conf.d
    command: /opt/sensu/bin/sensu-server -c /etc/sensu/config.json

  sensu-client2:
    build: .
    hostname: sensu-client2
    container_name: sensu-client2
    volumes:
      - ./sensu-client2/config.json:/etc/sensu/config.json
      - ./sensu-client2/conf.d:/etc/sensu/conf.d
    command: /opt/sensu/bin/sensu-client -c /etc/sensu/config.json

  sensu-api2:
    build: .
    hostname: sensu-api2
    container_name: sensu-api2
    ports:
      - "4568:4567"
    volumes:
      - ./sensu-api2/config.json:/etc/sensu/config.json
      - ./sensu-api2/conf.d:/etc/sensu/conf.d
    command: /opt/sensu/bin/sensu-api -c /etc/sensu/config.json

  sensu-redis2:
    image: redis
    hostname: sensu-redis2
    container_name: sensu-redis2

